package com.braservone.enums;

public enum TipoPoco {
	  POCO_EXPLORATORIO_PIONEIRO,
	  POCO_EXPLORATORIO_ESTRATIGRAFICO,
	  POCO_EXPLORATORIO_EXTENSAO,
	  POCO_EXPLORATORIO_PIONEIRO_ADJACENTE,
	  POCO_EXPLORATORIO_PROSPECTO_MAIS_RASO,
	  POCO_EXPLORATORIO_PROSPECTO_MAIS_PROFUNDO,
	  POCO_EXPLOTATORIO_PRODUCAO,
	  POCO_EXPLOTATORIO_INJECAO,
	  POCO_ESPECIAL,
	  POCO_ESTOCAGEM
}
